name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - run: docker run --name mongo -d -p 27017:27017 mongo
      - run: echo $PUB_CREDENTIALS > $HOME/.pub-cache/credentials.json
      - run: cd unpub && pub get && pub run test
